site_name: Cuckoo3 docs
site_url: https://cuckoo-hatch.cert.ee/static/docs/
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: cert-ee-light
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  logo: assets/images/cuckoo3-docs-round.png
  favicon: assets/images/favicon.png
  font: false
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
    - search.suggest
    - search.highlight
    - search.share

extra_css:
  - extra.css
#   - style.css

markdown_extensions:
- admonition
- attr_list
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.details
- toc:
    permalink: true

plugins:
- include-markdown
- search

docs_dir: src

nav:
- About:
  - Cuckoo3: about/cuckoo.md
  - Sandboxing: about/sandboxing.md
  - Terminology: about/terminology.md

- Installing:
  - Overview: installing/overview.md
  - System dependencies: installing/dependencies.md
  - Quickstart: installing/quickstart.md
  - VMCloak: installing/vmcloak.md
  - Cuckoo3: installing/cuckoo.md

- Configuring:
  - System dependencies: configuring/system.md
  - VMCloak: configuring/vmcloak.md
  - Cuckoo3: configuring/cuckoo.md
  - Web UI: configuring/web-ui.md
  - Web API: configuring/web-api.md
  - Network routing: configuring/routing.md

- Creating:
  - Virtual machines: creating/vms.md
  - Machinery modules: creating/machinery.md

- Using:
  - CLI API: using/cli-api.md
  - Web API: using/web-api-endpoints.md
  - Web UI: using/web-ui.md
  - Commands: using/commands.md

- Troubleshooting:
  - Common errors: faq/common.md
